version: "3"
services:
  redis:
    container_name: redis
    hostname: redis
    image: bitnami/redis:5.0.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami
    command: ./run.sh --notify-keyspace-events KA

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  mysql:
    container_name: mysql
    image: mysql:5.7
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    ports:
      - 8181:80
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local
