version: "3"
services:
  redis:
    container_name: redis
    hostname: redis
    image: bitnami/redis:5.0.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami
    command: ./run.sh --notify-keyspace-events KA

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  ## https://github.com/bitnami/bitnami-docker-mongodb/blob/master/docker-compose-replicaset.yml

  mongo1:
    image: "docker.io/bitnami/mongodb:4.4-debian-10"
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_KEY=replicaSet0
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=exchange
    volumes:
      - "mongo_data:/bitnami/mongodb"

  mongo2:
    image: "docker.io/bitnami/mongodb:4.4-debian-10"
    ports:
      - 27018:27017
    depends_on:
      - mongo1
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo2
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_KEY=replicaSet0

  mongo3:
    image: "docker.io/bitnami/mongodb:4.4-debian-10"
    ports:
      - 27019:27017
    depends_on:
      - mongo1
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo3
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_KEY=replicaSet0

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "rabbitmqErlangCookie"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/rabbitmq

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
  rabbitmq_data:
    driver: local
