version: "3"
services:
  redis:
    container_name: redis
    hostname: redis
    image: bitnami/redis:5.0.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami
    command: ./run.sh --notify-keyspace-events KA

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  mongo:
    image: mongo
    image: bitnami/mongodb:4.0
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=exchange
    volumes:
      - mongo_data:/mongo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
